#!/usr/bin/env bash
# Seed a PUBLIC GitHub repo for the code-fix path (replaces the old local-Gitea flow).
#
# What it does (run ONCE by the maintainer, or re-run to reset the upstream repo):
#   1. create/ensure a PUBLIC upstream repo  {OWNER}/{REPO}  (default branch = master)
#   2. build local git history:
#        commit 1 (clean baseline) — bounded recent-id cache: deque(maxlen=128)
#        commit 2 (planted leak)   — unbounded list  (the suspect deploy)
#      generated by sed from the fixture so the ONLY diff between the two commits is the
#      cache data structure -> the git diff the diagnose Agent sees is exactly the bug.
#   3. force-push that clean 2-commit history to the upstream repo's master
#   4. enable master branch protection (PRs only; nobody pushes master directly)
#   5. write deploys.log (image tag <-> git SHA <-> time) — the deploy-history trail
#
# Real-OSS demonstration model:
#   - This repo is PUBLIC. Each user FORKS it to their own account, then sets
#     GITHUB_FORK_OWNER=<their-username> + GITHUB_TOKEN=<their-PAT>. The code-fix Agent
#     clones THEIR fork, pushes a bugfix branch there, and opens a CROSS-FORK PR whose
#     base is THIS upstream repo. No collaborator invite needed; all PRs land here.
#   - The maintainer can also run the Agent directly (GITHUB_FORK_OWNER == OWNER) -> same-repo PR.
#
# Requires: `gh` (authenticated: gh auth status) and `git`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE="$ROOT/scripts/fixtures/recommendation"

OWNER="${GITHUB_UPSTREAM_OWNER:-HuaiNan54321}"
REPO="${GITHUB_REPO:-recommendation}"
DEFAULT_BRANCH="${GITHUB_DEFAULT_BRANCH:-master}"
GIT_EMAIL="${GITHUB_SEED_EMAIL:-aiops@example.com}"
GIT_NAME="${GITHUB_SEED_NAME:-aiops}"

command -v gh >/dev/null || { echo "[seed] gh CLI not found. Install: https://cli.github.com/"; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "[seed] gh not authenticated. Run: gh auth login"; exit 1; }

FULL="$OWNER/$REPO"

echo "[seed] ensuring PUBLIC repo $FULL exists…"
if gh repo view "$FULL" >/dev/null 2>&1; then
  echo "[seed] repo exists; ensuring it is public…"
  gh repo edit "$FULL" --visibility public --accept-visibility-change-consequences >/dev/null 2>&1 || true
else
  gh repo create "$FULL" --public \
    --description "AIOps example — buggy recommendation service (planted memory leak). Fork me and let the Agent open a PR." \
    >/dev/null
  echo "[seed] created $FULL (public)."
fi

# --- build local git history: clean commit, then planted-leak commit ---
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"
git init -q -b "$DEFAULT_BRANCH"
git config user.email "$GIT_EMAIL"
git config user.name "$GIT_NAME"

# commit 1: clean baseline — SAME runnable service as the leak revision, but the
# seen-id cache is BOUNDED (deque(maxlen=128)). Generated by sed from the fixture so
# the only difference vs the leak commit is the cache data structure.
cp "$FIXTURE/test_recommendation.py" "$FIXTURE/requirements.txt" "$FIXTURE/README.md" "$FIXTURE/Dockerfile" .
python3 - "$FIXTURE/recommendation_server.py" recommendation_server.py <<'PY'
import sys
src, dst = sys.argv[1], sys.argv[2]
code = open(src).read()
code = code.replace(
    "import threading\n",
    "import threading\nfrom collections import deque\n",
    1,
)
code = code.replace(
    "_seen_product_ids: list[str] = []",
    "_seen_product_ids: deque[str] = deque(maxlen=128)  # bounded: recent ids only",
)
code = code.replace(
    "s4 capstone — the \"bad\" (planted) revision.",
    "Clean baseline revision (bounded recent-id cache).",
)
open(dst, "w").write(code)
PY
git add -A && git commit -q -m "recommendation service baseline (bounded recent-id cache)"
CLEAN_SHA=$(git rev-parse --short HEAD)

# commit 2: PLANT the leak — replace the bounded deque with an unbounded list.
cp "$FIXTURE/recommendation_server.py" recommendation_server.py
git add -A && git commit -q -m "perf: track all seen product ids for analytics

Collect every requested product id so we can compute popularity later."
BAD_SHA=$(git rev-parse --short HEAD)

echo "[seed] pushing history (clean=$CLEAN_SHA, leak=$BAD_SHA) to ${FULL}…"
# Temporarily lift branch protection so the force-push (reset of history) can land.
gh api -X DELETE "repos/$FULL/branches/$DEFAULT_BRANCH/protection" >/dev/null 2>&1 || true
git remote add origin "https://github.com/$FULL.git"
# gh provides the credential helper, so no token needs to appear on the command line.
git -c credential.helper='!gh auth git-credential' push -q --force -u origin "$DEFAULT_BRANCH"

# --- master branch protection: PRs only ---
# enforce_admins=true is ESSENTIAL: without it the repo owner (you) can still push master
# directly, which breaks the demo's "推不上 master，只能提 PR" guarantee. required_pull_request_reviews
# (count 0) is what makes GitHub reject direct pushes with "Changes must be made through a pull request".
echo "[seed] enabling '$DEFAULT_BRANCH' branch protection (PRs only, enforced for admins too)…"
gh api -X PUT "repos/$FULL/branches/$DEFAULT_BRANCH/protection" \
  -H "Accept: application/vnd.github+json" \
  --input - >/dev/null 2>&1 <<'JSON' || \
  echo "[seed] (branch protection API returned non-2xx; re-run or set it in repo Settings > Branches)"
{
  "required_status_checks": null,
  "enforce_admins": true,
  "required_pull_request_reviews": { "required_approving_review_count": 0 },
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false
}
JSON

# --- deploy-history trail (diagnose Agent reads this in repo root) ---
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$ROOT/deploys.log" <<EOF
# service deploy history (image tag = git SHA)
$NOW  recommendation  image=recommendation:$CLEAN_SHA  sha=$CLEAN_SHA  note=baseline
$NOW  recommendation  image=recommendation:$BAD_SHA  sha=$BAD_SHA  note=LATEST_DEPLOY (suspect)
EOF

echo ""
echo "[seed] DONE."
echo "  upstream repo:  https://github.com/$FULL"
echo "  clean SHA:      $CLEAN_SHA"
echo "  leak  SHA:      $BAD_SHA  <-- latest deploy, the suspect commit"
echo "  deploys.log written to repo root"
echo ""
echo "  maintainer (same-repo PR):"
echo "    export GITHUB_TOKEN=\$(gh auth token)"
echo "    export GITHUB_UPSTREAM_OWNER=$OWNER GITHUB_REPO=$REPO"
echo "    # GITHUB_FORK_OWNER defaults to UPSTREAM_OWNER -> same-repo PR"
echo ""
echo "  user (fork + cross-fork PR — no invite needed):"
echo "    1) Fork https://github.com/$FULL to your account"
echo "    2) Create a PAT (scope: public_repo) at https://github.com/settings/tokens"
echo "    3) export GITHUB_TOKEN=<your-PAT>"
echo "       export GITHUB_UPSTREAM_OWNER=$OWNER GITHUB_REPO=$REPO"
echo "       export GITHUB_FORK_OWNER=<your-github-username>"
